### ISSUE TITLE
PHP Executable using Docker

### ISSUE THREAD

**Issue by webrgp** [moetelo/twiggy#23]
Before I get to my question: THANK YOU! I really didn't want to have to move PHPStorm just to get autocomplete for Twig in VSCode.

With that out of the way, how should I configure `phpExecutable` with Docker? In one of the project I am working with, if I wanted to get the PHP version in the container I use:

```
docker-compose exec web sh -c "php -v"
```

Can you also provide an example for DDEV?

**Comment by moetelo** [comment]
> didn't want to have to move PHPStorm just to get autocomplete for Twig in VSCode

Same here! That's why it exists.

-----

For the php things to work, the containerized `phpExecutable` must be able to call commands like:
`$phpExecutable path/to/php/files/file.php`

During the process of the language server, it calls commands like:
`$phpExecutable $pathToYourProject/vendor/autoload.php`
`$phpExecutable $pathToExtension/dist/phpUtils/printCraftTwigEnvironment`

In my case, the `phpExecutable` for dockerized environment looks like this:
`"twiggy.phpExecutable": "docker compose exec php php"`
Which means "in container named php, use php".

So, to achieve this, the following command must work correctly:
`docker compose exec php php /home/username/projects/my-project/vendor/autoload.php`
`docker compose exec php php /home/username/.vscode/extensions/moetelo.twiggy-0.9.2/dist/phpUtils/printCraftTwigEnvironment`

(replace username in the path with your actual `whoami`)

-----

The container knows nothing about your filesystem, and it has no `/home/username/` directory in it:
```bash
docker compose exec web ls /home/username/

-> ls: cannot access '/home/username/': No such file or directory
```

We have to somehow expose those files to it.

I've sorted this out by using the [bind mounts](https://docs.docker.com/storage/bind-mounts/).

In the `compose.yml` or, better, `docker-compose.override.yml`:

```
services:
  web: # your php container name here
    volumes:
      - type: bind
        source: /home/username/projects/my-project/
        target: /home/username/projects/my-project/
      - type: bind
        source: /home/username/.vscode/extensions/moetelo.twiggy-0.9.2/dist/phpUtils/
        target: /home/username/.vscode/extensions/moetelo.twiggy-0.9.2/dist/phpUtils/
```

(please correct me if there is a shorter syntax for this)

After restarting my container (`down`, `up -d`), this command works:
`docker compose exec php php /home/mikhail/.vscode/extensions/moetelo.twiggy-0.9.2/dist/phpUtils/printCraftTwigEnvironment /home/mikhail/projects/craft-project`

And now the extension works for me.

-----

Note that the extension path is hardcoded in the bind mount (`/.vscode/extensions/moetelo.twiggy-0.9.2/`), and after each extension update you'll have to reconfigure this again.

Please tell me whether this works for you or not!
